server:
  port: 8013


spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 192.168.43.29:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public